### ISSUE TITLE
LAPACK ArmPL backend doesn't compile with ArmPL 25.04

### ISSUE THREAD

**Issue by rafbiels** [oneapi-src/oneMKL#666]
# Summary
ArmPL 25.04 has the following change in the release notes:
>By default Arm Performance Libraries now uses C++ std::complex types when compiled with C++ programs.

https://developer.arm.com/documentation/109681/2504/Release-overview/Differences-from-previous-release/Additions-and-changes-?lang=en

Presumably this is the cause of a compilation failure of oneMath LAPACK ArmPL backend:
```
In file included from /work/oneMath/src/lapack/backends/armpl/armpl_wrappers.cpp:23:
/work/oneMath/src/lapack/backends/armpl/armpl_common.hpp:145:16: error: cannot convert 'std::complex<float>' to 'std::int64_t' (aka 'long') without a conversion operator
  145 |         return static_cast<std::int64_t>((*((T*)&alpha)));
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

# Version
3f8f4f309c7a7038ec0e84d7795d316d11435652

# Environment
* Arm Neoverse-V1 CPU
* arm-performance-libraries_25.04.1_deb_gcc
* Ubuntu 24.04
* Open-source DPC++ tag `nightly-2025-04-01`

# Steps to reproduce
```
cmake \
  -DTARGET_DOMAINS=lapack \
  -DENABLE_MKLCPU_BACKEND=off -DENABLE_MKLGPU_BACKEND=off \
  -DENABLE_ARMPL_BACKEND=on -DARMPL_ROOT=/path/to/armpl \
  -B build-lapack -G Ninja -DREF_LAPACK_ROOT=/path/to/netlib/
cmake --build build-lapack
```

# Observed behavior
Compilation failure

# Expected behavior
Compilation succeeds

**Comment by rafbiels** [comment]
@adegomme would you be able to look into this as the author of the code?

**Comment by adegomme** [comment]
Hi, indeed, and this change should make it easier in the future. I added a small patch that should hopefully help in this case. 
Tests should pass now, but I'll still have to check if the return value for the scratchpad size is actually given correctly in real() by the lib, but this will have to wait a bit.
Thanks for the report

**Comment by sknepper** [comment]
PR #667 was merged; @rafbiels , please verify that it fixes this ominous issue and close if so. Thanks!

**Comment by rafbiels** [comment]
I can confirm the backend works well with the head of the `develop` branch now. Many thanks @adegomme for the prompt fix!
